---
title: "Historical decrease in agricultural landscape diversity is associated with shifts in bumble bee species occurrence"
date: 2021-04-26
author:
  - name: Jeremy Hemberger
    url: https://jhemberger.github.io
    orcid: 0000-0003-3648-4724
    affiliation: University of Wisconsin-Madison
  - name: Michael Crossley
    url: https://www.udel.edu/academics/colleges/canr/departments/entomology-and-wildlife-ecology/faculty-staff/michael-crossley/
    orcid: 0000-0003-3140-6620
    affiliation: University of Georgia
  - name: Claudio Gratton
    url: https://gratton.entomology.wisc.edu/
    orcid: 0000-0001-6262-9670
    affiliation: University of Wisconsin-Madison
categories:
 - agricultural intensification
 - bombus
 - crop diversity 
 - ecoinformatics
pub-info:
  reference: >-
    Jeremy Hemberger, Michael Crossley, Claudio Gratton, “Historical decrease in agricultural landscape diversity is associated with shifts in bumble bee species occurrence” <em>Ecology Letters</em> 2021, doi: <a href="https://doi.org/10.1111/ele.13786"><code>10.1111/ele.14492</code></a>
  links:
    - name: Final version
      url: ele.13786.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Code
      url: https://doi.org/10.6084/m9.figshare.14461828
      icon: fa-solid fa-code
doi: 10.1111/ele.13786
---

## Abstract
Agricultural intensification is a key suspect among putative drivers of recent insect declines, but an explicit link between historical change in agricultural land cover and insect occurrence is lacking. Determining whether agriculture impacts beneficial insects (e.g. pollinators), is crucial to enhancing agricultural sustainability. Here, we combine large spatiotemporal sets of historical bumble bee and agricultural records to show that increasing cropland extent and decreasing crop richness were associated with declines in over 50\% of bumble bee species in the agriculturally intensive Midwest, USA. Critically, we found that high crop diversity was associated with a higher occurrence of many species pre‐1950 even in agriculturally dominated areas, but that current agricultural landscapes are devoid of high crop diversity. Our findings suggest that insect conservation and agricultural production may be compatible, with increasing on‐farm and landscape‐level crop diversity predicted to have positive effects on bumble bees. Agricultural intensification is a key suspect among putative drivers of recent insect declines, but an explicit link between historical change in agricultural land cover and insect occurrence is lacking. Here, we find that historical patterns of agricultural intensification are strongly related to patterns in bumble bee species occurrence, specifically a loss in crop species richness and increased cropland proportion.

## Important figures

![<strong>Figure 1:</strong> Patterns of agricultural intensification from 1880 to 2017 at roughly equal intervals across Illinois, Indiana, Iowa, Michigan, Minnesota and Wisconsin in two metrics: (a and b) proportion of county in cropland and (c and d) number of crops grown per county. Inset graphs (b and d) depict the general trend of these variables for each state in the study area.](fig1.jpg)

![<strong>Figure 2:</strong> Illustration of the temporal trend in predicted bumble bee occurrence across the six focal species (a–f). We use the species‐specific models which predict the probability of occurrence given cropland proportion and number of crops (with all interactions) to plot the expected county‐level probability for each census year of the model. With this information, for each species, we estimated a county‐level time series (GAM‐fits, black lines) as well as an overall trend in the predicted probability of occurrence (red lines) for the species. For each county and species, we use the average slope (i.e. temporal change) to create a spatial representation of the trend in predicted species occurrence given local agricultural conditions, where yellow, gold, and black indicate increasing, stable, and decreasing probability of occurrence over time respectively. Together, these panels depict the long‐term occurrence trend of each species as predicted by the agricultural intensification metrics (cropland proportion and number of crops), smoothing over short‐term fluctuations in predicted occurrence for in any single census year.](fig2.jpg)

## Citation

``` bibtex
@article{Hemberger.2021, 
year = {2021}, 
title = {{Historical decrease in agricultural landscape diversity is associated with shifts in bumble bee species occurrence}}, 
author = {Hemberger, Jeremy and Crossley, Michael S. and Gratton, Claudio}, 
journal = {Ecology Letters}, 
issn = {1461-023X}, 
doi = {10.1111/ele.13786}, 
pmid = {34143928}, 
pages = {1800--1813}, 
number = {9}, 
volume = {24}, 
keywords = {}
}
```
